### ISSUE TITLE
About email settings

### ISSUE THREAD

**Issue by XuCcc** [zjlywjh001/phrackCTF-Personal-Docker#1]
My spring-settings

```xml
		<!-- 服务器 -->
		<property name="host" value="smtp.163.com" />
		<!-- 端口号 -->
		<property name="port" value="465" />
		<!-- 用户名 -->
		<property name="username" value="XXX" />
		<!-- 密码 -->
		<property name="password" value="XXX" />
```

And the logs show

```shell
logs/./catalina.out:org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.163.com, port: 465;
logs/./catalina.out-  nested exception is:
logs/./catalina.out:    javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.163.com, port: 465;
logs/./catalina.out-  nested exception is:
logs/./catalina.out-    javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; message exception details (1) are:
logs/./catalina.out-Failed message 1:
logs/./catalina.out:javax.mail.MessagingException: Could not connect to SMTP host: smtp.163.com, port: 994;
logs/./catalina.out-  nested exception is:
logs/./catalina.out-    javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
logs/./catalina.out-    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
logs/./catalina.out-    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
logs/./catalina.out-    at javax.mail.Service.connect(Service.java:295)
```

**Comment by zjlywjh001** [comment]
163 mail is tested on my own computer. This exception seemed your JRE does not trust the cert of smtp.163.com,you can try set email  without ssl. 
```<prop key="mail.smtp.ssl.enable">false</prop>```

**Comment by XuCcc** [comment]
I set the ssl to false,then enable the debug,it shows
```shell
logs/./catalina.out:com.sun.mail.smtp.SMTPSendFailedException: 553 Mail from must equal authorized user
logs/./catalina.out-;
logs/./catalina.out-  nested exception is:
logs/./catalina.out:    com.sun.mail.smtp.SMTPSenderFailedException: 553 Mail from must equal authorized user
logs/./catalina.out-
logs/./catalina.out:    at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108)
logs/./catalina.out:    at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609)
logs/./catalina.out:    at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117)
logs/./catalina.out:    at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
logs/./catalina.out:    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
logs/./catalina.out:    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
logs/./catalina.out-    at top.phrack.ctf.utils.MailUtil.sendPasswordResetMail(MailUtil.java:45)
logs/./catalina.out-    at top.phrack.ctf.utils.MailUtil$$FastClassBySpringCGLIB$$a9d38835.invoke(<generated>)
logs/./catalina.out-    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
logs/./catalina.out-    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
logs/./catalina.out-    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
--
logs/./catalina.out:Caused by: com.sun.mail.smtp.SMTPSenderFailedException: 553 Mail from must equal authorized user
logs/./catalina.out-
logs/./catalina.out:    at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1616)
logs/./catalina.out-    ... 12 more
logs/./catalina.out-QUIT
logs/./catalina.out-221 Bye
logs/./catalina.out:org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 553 Mail from must equal authorized user
logs/./catalina.out-;
logs/./catalina.out-  nested exception is:
logs/./catalina.out:    com.sun.mail.smtp.SMTPSenderFailedException: 553 Mail from must equal authorized user
logs/./catalina.out-; message exception details (1) are:
logs/./catalina.out-Failed message 1:
logs/./catalina.out:com.sun.mail.smtp.SMTPSendFailedException: 553 Mail from must equal authorized user
```

i changed `/config/mail.properties`

set the value of **mail.sendfrom**  as the same as the **username** in `config/spring-mail.xml`

it works!

i found the mail in QQ Junk-box 

THX!
